apiVersion: v1
kind: Service
metadata:
  name: jupyterlab
  namespace: jupyterlab
  labels:
    name: jupyterlab
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8888
      protocol: TCP
      name: http
      nodePort: 32000
  selector:
    name: jupyterlab